CREATE TABLE entry (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type             TEXT   NOT NULL CHECK (type IN ('log', 'note')),
  title            TEXT   NOT NULL DEFAULT '',
  content_md       TEXT   NOT NULL,
  content_plain    TEXT   NOT NULL,
  parent_id        BIGINT REFERENCES entry (id),
  source_date      DATE   NOT NULL,
  review_status    TEXT   NOT NULL DEFAULT 'none'
                   CHECK (review_status IN ('none', 'learning', 'mastered')),
  mastery          SMALLINT NOT NULL DEFAULT 0,
  next_review_at   TIMESTAMPTZ NULL,
  review_count     INT    NOT NULL DEFAULT 0,
  last_reviewed_at TIMESTAMPTZ NULL,
  pinned           BOOLEAN NOT NULL DEFAULT FALSE,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  deleted_at       TIMESTAMPTZ NULL
);

CREATE INDEX idx_entry_timeline   ON entry (type, source_date DESC) WHERE deleted_at IS NULL;
CREATE INDEX idx_entry_review     ON entry (review_status, next_review_at) WHERE deleted_at IS NULL;
CREATE INDEX idx_entry_parent     ON entry (parent_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_entry_title_trgm ON entry USING gin (title gin_trgm_ops);
CREATE INDEX idx_entry_plain_trgm ON entry USING gin (content_plain gin_trgm_ops);

CREATE TABLE entry_link (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  src_id     BIGINT NOT NULL REFERENCES entry (id) ON DELETE CASCADE,
  dst_id     BIGINT NOT NULL REFERENCES entry (id) ON DELETE CASCADE,
  link_type  TEXT   NOT NULL DEFAULT 'ref',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT uk_entry_link UNIQUE (src_id, dst_id, link_type),
  CONSTRAINT ck_entry_link_self CHECK (src_id <> dst_id)
);

CREATE INDEX idx_link_dst ON entry_link (dst_id);

CREATE TABLE tag (
  id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE
);

CREATE TABLE entry_tag (
  entry_id BIGINT NOT NULL REFERENCES entry (id) ON DELETE CASCADE,
  tag_id   BIGINT NOT NULL REFERENCES tag (id)   ON DELETE CASCADE,
  PRIMARY KEY (entry_id, tag_id)
);
